_target_: graspsampling.hands.URDFHand
file_name: robotiq_3f_clean.urdf
grasp_frame: palm
maximum_aperture: 0.16
approach_direction: [0., 0., 1.]
open_configurations:
  - [0.]
close_configurations:
  - [0.7]
width: 0.16163334
depth: 0.10477500
closing_regions:
  - extents: [0.16, 0.02, 0.06]
    translation: [0.0, 0.0, 0.105]
    rotation_wxyz: [1., 0., 0., 0.]
contact_points:
  - link_name: finger_a_link_3
    location: [-0.08, 0, 0.105]
    normal: [1., 0., 0.]
  - link_name: finger_b_link_3
    location: [0.08, 0, 0.105]
    normal: [-1., 0., 0.]
transform_offset_from_asset_to_graspgen_convention: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
symmetric_antipodal: False
